variables:
  MVN_LOCAL_REPO: "$CI_PROJECT_DIR/.m2/repository"
  GITLIBS: "$CI_PROJECT_DIR/.gitlibs"
  # using with optimized gitlab-runner instance (docker executor)
  # HOME: /root
  # MVN_LOCAL_REPO: "$HOME/.m2/repository"
  # GITLIBS: "$HOME/.gitlibs"



# caching don't works for outside repository
cache:
  paths:
    - .m2/repository
    - .gitlibs


before_script:
  - uname -a


test:
  only:
    - master
  tags:
    - docker
  image: clojure:openjdk-8-tools-deps-alpine
  script:
    - clojure -Sdeps "{:mvn/local-repo \"$MVN_LOCAL_REPO\"}" -Stree
    - clojure -Sdeps "{:mvn/local-repo \"$MVN_LOCAL_REPO\"}" -m gitlab-ci-clojure-example.main
